const T={zh:{eyebrow:"猜數字遊戲",title:"幾 A 幾 B",subtitle:"猜出隱藏答案。A 代表字元與位置都正確；B 代表字元正確但位置錯誤。",restart:"重新開始",settings:"遊戲設定",guessSection:"猜測",changeSettings:"修改設定",mode:"遊戲模式",length:"答案位數",start:"開始遊戲",attempts:"猜測次數",chars:"可用字元：",hint:"目前提示：",notGuessed:"尚未猜測",guessLabel:"輸入猜測",guessPlaceholder:"輸入答案，例如 1234",guess:"猜！",history:"猜測紀錄",clear:"清除",empty:"還沒有猜測紀錄",max:"最多",unit:"位",range:"位數必須介於 1 到 {max}。",exact:"請輸入剛好 {length} 個字元。",invalid:"只能使用：{chars}",duplicate:"不能有重複字元。",correct:"猜中了！答案是 {answer}，總共猜了 {count} 次。",score:"{a}A {b}B",lang:"English"},en:{eyebrow:"Number Guessing Game",title:"Bulls and Cows",subtitle:"Guess the hidden answer. A means the character and position are both correct; B means the character is correct but in the wrong position.",restart:"Restart",settings:"Game Settings",guessSection:"Guess",changeSettings:"Change Settings",mode:"Game Mode",length:"Answer Length",start:"Start Game",attempts:"Attempts",chars:"Available characters: ",hint:"Current hint: ",notGuessed:"No guess yet",guessLabel:"Enter your guess",guessPlaceholder:"Enter a guess, e.g. 1234",guess:"Guess!",history:"Guess History",clear:"Clear",empty:"No guesses yet",max:"Maximum",unit:"characters",range:"Length must be between 1 and {max}.",exact:"Please enter exactly {length} characters.",invalid:"Only these characters are allowed: {chars}",duplicate:"Characters cannot be repeated.",correct:"Correct! The answer is {answer}. You solved it in {count} attempts.",score:"{a}A {b}B",lang:"繁體中文"}};
const N={zh:{10:"10 進位",16:"16 進位",36:"36 進位"},en:{10:"Base 10",16:"Base 16",36:"Base 36"}}, C={10:"0123456789",16:"0123456789ABCDEF",36:"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"};
let lang=localStorage.getItem("nAnB-language")||"zh",answer="",mode=10,len=4,tries=0,hist=[];
const $=id=>document.getElementById(id), t=(k,v={})=>Object.entries(v).reduce((s,[a,b])=>s.replaceAll(`{${a}}`,b),T[lang][k]);
function language(){document.documentElement.lang=lang==="zh"?"zh-Hant":"en";document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll("[data-ph]").forEach(e=>e.placeholder=t(e.dataset.ph));$("lang").textContent=t("lang");[...$("mode").options].forEach(o=>o.textContent=N[lang][o.value]);hintLength();render()}
function hintLength(){let m=+$("mode").value;$("length").max=m;$("lengthHint").textContent=`${t("max")} ${m} ${t("unit")}`}
function randomAnswer(){let a=C[mode].split("");for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,len).join("")}
function showSettings(){$("settingsSection").classList.remove("hidden");$("gameSection").classList.add("hidden")}
function start(){mode=+$('"'"'mode'"'"').value;len=+$('"'"'length'"'"').value;if(!Number.isInteger(len)||len<1||len>mode){$('"'"'message'"'"').textContent=t('"'"'range'"'"',{max:mode});return}answer=randomAnswer();tries=0;hist=[];$('"'"'attempts'"'"').textContent=0;$('"'"'chars'"'"').textContent=C[mode];$('"'"'message'"'"').textContent="";$('"'"'guess'"'"').disabled=false;$('"'"'guess'"'"').maxLength=len;$('"'"'hint'"'"').textContent=t('"'"'notGuessed'"'"');$('"'"'settingsSection'"'"').classList.add('"'"'hidden'"'"');$('"'"'gameSection'"'"').classList.remove('"'"'hidden'"'"');render();$('"'"'guess'"'"').focus()}
function score(g){let a=0,b=0;for(let i=0;i<len;i++)g[i]===answer[i]?a++:answer.includes(g[i])&&b++;return{a,b}}
function submit(e){e.preventDefault();let g=$("guess").value.trim().toUpperCase(),set=new Set(C[mode]);$("guess").value=g;if(g.length!==len){$("message").textContent=t("exact",{length:len});return}if([...g].some(x=>!set.has(x))){$("message").textContent=t("invalid",{chars:C[mode]});return}if(new Set(g).size!==g.length){$("message").textContent=t("duplicate");return}let r=score(g);tries++;hist.unshift({guess:g,...r});$("attempts").textContent=tries;$("hint").textContent=r.a===len?t("correct",{answer,count:tries}):t("score",r);render();if(r.a===len)$("guess").disabled=true}
function render(){let h=$("history");if(!hist.length){h.innerHTML=`<p class="empty">${t("empty")}</p>`;return}h.innerHTML=hist.map((x,i)=>`<div class="item"><span>#${hist.length-i}</span><code>${x.guess}</code><strong>${t("score",x)}</strong></div>`).join("")}
$("mode").onchange=hintLength;$("start").onclick=start;$("restart").onclick=start;$("clear").onclick=()=>{hist=[];tries=0;$("attempts").textContent=0;$("hint").textContent=t("notGuessed");$("message").textContent="";$("guess").disabled=false;render()};$("form").onsubmit=submit;$("lang").onclick=()=>{lang=lang==="zh"?"en":"zh";localStorage.setItem("nAnB-language",lang);language()};language();showSettings();